### ISSUE TITLE
plugin manager: no binaries

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-app#111]
**Describe the solution you'd like**
I think it would be very handy to have a "update binaries" checkbox when updating a plugin. Often I update plugins on a production system and I dont want to download/compile/etc latest binaries that come with the plugin code.

**Describe alternatives you've considered**
scipion installp -p xxx --no-Bin

**Comment by pconesa** [comment]
Thanks! makes perfect sense. Maybe even taking a default value from the env? Otherwise, In the case you are describing, you should not forget to activate it.

**Comment by azazellochg** [comment]
I guess the checkbox could be checked by default as now. Not sure that we need more variables in config. It's good to have flexibility but overmanagement is also not nice. There are too many already :))

**Comment by pconesa** [comment]
Ok, no env var!
