### ISSUE TITLE
workflow_tutorial_intro.json  depends on ProtCTFFind which isn't available anymore

### ISSUE THREAD

**Issue by akesandgren** [scipion-em/scipion-app#149]
**Describe the bug**
The intro tutorial depends on ProtCTFFind which was available in scipion-em-grigoriefflab, but that one has been deprecated.

**To Reproduce**
1. Try to run "scipion tutorial intro" using Scipion3

**Comment by pconesa** [comment]
Thanks for reporting, I'll update the tutorial
