### ISSUE TITLE
best linux distro for installing Scipion

### ISSUE THREAD

**Issue by ckywong** [scipion-em/scipion-app#177]
I just wonder if there is one Linux distro you would recommend for installing Scipion.  I am thinking of creating an apptainer image for Scipion and curious if there is one distro that works better than others for Scipion.  Thank you!

**Comment by pconesa** [comment]
Hi! Most os our users use ubuntu, but it works with other distros like CentOS. Theoretically any would work but installation may be less smooth.

Please, let us know if you need any help and once ready we can add this resource (if shareable) in our website or doc site.

Cheers.
