### ISSUE TITLE
error in tutorial script

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-app#19]
**Describe the bug**
https://github.com/scipion-em/scipion-app/blob/devel/scipion/scripts/tutorial.py#L62 loadWorkflow is not defined in Tutorial class, but defined in child classes. Is it gonna work like this?

https://github.com/scipion-em/scipion-app/blob/devel/scipion/scripts/tutorial.py#L62

**Comment by pconesa** [comment]
We'll add an empty loadWorkflow method. Is that what you are referring too, right?

**Comment by azazellochg** [comment]
yes
