### ISSUE TITLE
allow non-tgz installations

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-app#30]
I want install script to use non-tgz files. For example, I have:
```
env.addPackage('eman', version='2.31',
                       url='https://cryoem.bcm.edu/cryoem/static/software/release-2.31/eman2.31_sphire1.3.linux64.sh',
                       commands=eman231_commands)
```
Can install script NOT assume that everything it downloads is tgz by default and NOT try to untar it. So I can run commands instead myself?

**Comment by pconesa** [comment]
As a workaround, you can use void.tgz.

I'll leave it open until we actually remove that restriction.

**Comment by pconesa** [comment]
This is already possible: https://github.com/scipion-em/scipion-app/commit/f71e351334736b31987ce7bdf89eac403d1890f6
