### ISSUE TITLE
Import volumes viewer slices axis

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-app#86]
In the import volume viewer, when the map is visualized with slices, is not possible to change the axis view.

Only when the map is open with in the bottom menu (where the integrated console and the input-output are described) is posible to change the axis view

**Comment by pconesa** [comment]
I can do both: Am I missing anything?

**Comment by Vilax** [comment]
After updating my scipion it works. 

Thank you, @pconesa
