### ISSUE TITLE
scipion.template is outdated

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-app#93]
scipion-app/scipion/templates/scipion.template is outdated. It contains software variable which don't exist anymore like gempicker, nysbc. Also the list is incomplete. Shall we get rid of that list?

@pconesa I think you also told me that "In section PLUGINS, option CHIMERA_HOME exists in the template but not in the configuration file. Use --update parameter to update local config files." message is not true anymore since it looks not at this template file but at the environment. This message should be amended or corrected.

**Comment by pconesa** [comment]
Is not used anymore after recent fixes.
